### ISSUE TITLE
Empty context

### ISSUE THREAD

**Issue by lorelupo** [rbawden/Large-contrastive-pronoun-testset-EN-FR#3]
Hi, 

I have noticed that there are some blank lines in the extracted context files, as if there were no context for certain sentences.
For instance, line n. 7697 in file _OpenSubs.c1.context.src_, right after sentence "One mile from the exit, it starts shaking, violently shaking like it's having a nervous breakdown."
Is this normal?

Thanks

**Comment by rbawden** [comment]
I checked the original data (in the separate documents from OpenSubtitles) and lines 7697 and 7698 in OpenSubs.current.src ("At the health club, people are working out and they're training...") correspond to the first lines of a document (1992/1992_697738_4618033.en). So that's why these two lines are empty in OpenSubs.c1.context.src - there is no previous context to give and the choice was to leave them blank to indicate the beginning of documents. You might want to replace them with a symbol indicating that these are the start of a document, explicitly saying that there is no context.

**Comment by lorelupo** [comment]
OK, thank you!
